# Generated by Django 4.2.6 on 2023-11-22 02:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(help_text='*Maximum 20 characters', max_length=20, verbose_name='Name of the Author')),
                ('description', models.TextField(blank=True, verbose_name='Description of the blog')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'All Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(help_text='*Maximum 20 characters', max_length=20, verbose_name='Name of the Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'All Category',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='max 20 characters', max_length=20, verbose_name='tag name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'All Tags',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='Title of the blog')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description of the blog')),
                ('is_check', models.BooleanField(default=False, verbose_name='Is the Blog checked?')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='blog/poster', verbose_name='Poster of Blog')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Author of the Blog')),
                ('blog_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='name of blog category')),
                ('tag_name', models.ManyToManyField(to='blog.tags')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'All Blogs',
            },
        ),
    ]
