# Generated by Django 4.2.6 on 2023-12-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title_az',
            field=models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Title of the blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='title_en',
            field=models.CharField(help_text='Maximum 100 characters', max_length=100, null=True, verbose_name='Title of the blog'),
        ),
    ]
