# Generated by Django 4.2.6 on 2023-12-19 17:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_title_az_blogs_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description of the blog'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description of the blog'),
        ),
    ]
